apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prometheus-json-exporter
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      service: *app
  interval: 5m
  path: ./apps/base/prometheus-json-exporter/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
