apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/base/projects/kube-cats/kustomize.yaml
  - ./namespace.yaml
commonLabels:
  cluster: homelab
  group: projects
