apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/base/dragonfly-operator/kustomize.yaml
  - ./namespace.yaml
commonLabels:
  cluster: homelab
  group: database
