apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/base/snapshot-controller/kustomize.yaml
  - ../../../../apps/base/csi-driver-nfs/kustomize.yaml
  - ../../../../apps/base/metrics-server/kustomize.yaml
commonLabels:
  cluster: homelab
