apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: homelab
spec:
  config:
    server:
      root_url: "https://grafana.j6n.dev"
    # OIDC
    auth:
      signout_redirect_url: "https://auth.j6n.ca/application/o/grafana/end-session/"
      disable_login_form: "true"
      oauth_allow_insecure_email_lookup: "true"

    auth.generic_oauth:
      name: "authentik"
      enabled: "true"
      scopes: "openid email profile"
      auth_url: "https://auth.j6n.ca/application/o/authorize/"
      token_url: "https://auth.j6n.ca/application/o/token/"
      api_url: "https://auth.j6n.ca/application/o/userinfo/"
      # Map user groups to Grafana roles
      role_attribute_path: "contains(groups[*], 'grafana_admin') && 'Admin' || contains(groups[*], 'grafana_editor') && 'Editor' || 'Viewer'"
    # Enable public viewer
    auth.anonymous:
      enabled: "true"
      org_name: "Main Org."
      org_role: "Viewer"
      hide_version: "true"

    feature_toggles:
      externalServiceAccounts: "true"

    panels:
      enable_alpha: "true"
    unified_alerting:
      enabled: "false"
  # Default secret with admin credentials is disabled as the username and password are supplied externally
  disableDefaultAdminSecret: true
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: grafana-admin
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: grafana-admin
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                      name: grafana-oidc
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                      name: grafana-oidc
