apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: homelab
spec:
  config:
    server:
      root_url: "https://grafana.j6n.dev"
    # OIDC
    auth:
      signout_redirect_url: "https://auth.j6n.ca/application/o/grafana/end-session/"
      disable_login_form: "true"
      oauth_allow_insecure_email_lookup: "true"

    auth.generic_oauth:
      name: "authentik"
      enabled: "true"
      scopes: "openid email profile"
      auth_url: "https://auth.j6n.ca/application/o/authorize/"
      token_url: "https://auth.j6n.ca/application/o/token/"
      api_url: "https://auth.j6n.ca/application/o/userinfo/"
      # Map user groups to Grafana roles
      role_attribute_path: "contains(groups[*], 'grafana_admin') && 'Admin' || contains(groups[*], 'grafana_editor') && 'Editor' || 'Viewer'"
    # Enable public viewer
    auth.anonymous:
      enabled: "true"
      org_name: "Main Org."
      org_role: "Viewer"
      hide_version: "true"

    feature_toggles:
      externalServiceAccounts: "true"
    dashboards:
      default_home_dashboard_path: /var/lib/grafana/dashboards/home.json
    panels:
      enable_alpha: "true"
    unified_alerting:
      enabled: "false"
    serviceMonitor:
      enabled: "false"
  # Default secret with admin credentials is disabled as the username and password are supplied externally
  disableDefaultAdminSecret: true
  deployment:
    spec:
      template:
        spec:
          # The volumes for dashboards and provisioning config
          volumes:
            - name: dashboards
              emptyDir: {}
            - name: provisioning-config
              configMap:
                name: provisioning-config
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_USER
                      name: grafana-admin
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GF_SECURITY_ADMIN_PASSWORD
                      name: grafana-admin
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                      name: grafana-oidc
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                      name: grafana-oidc
              volumeMounts:
                - mountPath: /etc/grafana/provisioning/dashboards
                  name: provisioning-config
                - mountPath: /var/lib/grafana/dashboards
                  name: dashboards
            # This container watches the namespace for configmaps with the `dashboards` label
            # and creates files for all their keys under `FOLDER`
            - image: "ghcr.io/kiwigrid/k8s-sidecar:1.24.5"
              name: k8s-sidecar
              env:
                - name: LABEL
                  value: "grafana_dashboard"
                - name: LABEL_VALUE
                  value: "1"
                - name: FOLDER
                  value: /var/lib/grafana/dashboards
                - name: NAMESPACE
                  value: ALL
                - name: RESOURCE
                  value: configmap
              volumeMounts:
                - mountPath: /var/lib/grafana/dashboards
                  name: dashboards
