apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: home-dashboard
    files:
      - ../../../../dashboards/system/home.json

generatorOptions:
  annotations:
    grafana_folder: System
  labels:
    grafana_dashboard: "1"
  disableNameSuffixHash: true

resources:
  - ./externalsecrets.yaml
  - ./grafana.yaml
  - ./datasources.yaml
  - ./folders.yaml
  - ./dashboards.yaml
  - ./clusterrole.yaml
