apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: gatus-alerts
  files:
  - ../../../../dashboards/system/gatus_endpoints.json

generatorOptions:
  annotations:
    grafana_folder: System
  labels:
    grafana_dashboard: "1"
  disableNameSuffixHash: true

resources:
  - ./alerts.yaml
