apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./helmrelease.yaml
  # - ./externalsecrets.yaml
  - ./cobblemon/helmrelease.yaml
  - ./cobblemon/externalsecrets.yaml
  - ./cobblemon_academy/helmrelease.yaml
  - ./cobblemon_academy/externalsecrets.yaml
